#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "${2}" ]; then
            deb-systemd-helper disable jdownloader.service >/dev/null || true
            deb-systemd-invoke stop jdownloader.service >/dev/null || true
        fi

        SERVICE_XPATH_NAME="jdownloader"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! getent passwd jdownloader >/dev/null 2>&1; then
            echo "Adding jdownloader user..."
            useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin jdownloader
        else
            echo "jdownloader user already exists."
        fi

        if [ -e /var/run/jdownloader ]; then
            echo "Cleaning old pid file..."
            rm -Rf /var/run/jdownloader
        fi

        if [ ! -e /opt/jdownloader/JDownloader.jar ]; then
            echo "Extracting archive..."
            tar zxvf /opt/jdownloader/jdownloader.tar.gz -C /
            rm -Rf /opt/jdownloader/jdownloader.tar.gz
            chmod 775 /opt/jdownloader -R
            chown jdownloader:users /opt/jdownloader -R
        fi

        chmod 775 /opt
        chown root:users /opt

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "showtab" "0"
            omv_config_add_element "${SERVICE_XPATH}" "jderror" ""
            omv_config_add_element "${SERVICE_XPATH}" "uniqueid" ""
            omv_config_add_element "${SERVICE_XPATH}" "download-sharedfolderref" ""
            omv_config_add_element "${SERVICE_XPATH}" "download-dir" ""
        fi

        if ! omv_config_exists "/config/services/jdownloader/download-sharedfolderref"; then
            object="<download.sharedfolderref></download-sharedfolderref>"
            object="${object}<download-dir></download-dir>"
            omv_config_add_element "/config/services" "jdownloader" "${object}" true
        fi

        # Migrations.
        if dpkg --compare-versions "$2" lt-nl "3.2"; then
            omv_config_rename "${SERVICE_XPATH}/download.sharedfolderref" "download-sharedfolderref"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
