#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        systemctl stop jdownloader.service || :

        SERVICE_XPATH_NAME="jdownloader"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_delete "${SERVICE_XPATH}"
        fi

        if [ -d /opt/jdownloader ]; then
            rm -Rf /opt/jdownloader >/dev/null
        fi

        if getent passwd jdownloader >/dev/null 2>&1; then
            userdel -rf jdownloader
        fi

        if [ ! -d /opt ]; then
            mkdir /opt
            chmod 775 /opt
        fi
    ;;

    remove)
    ;;

        remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
